/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogPanel.java
 *
 * Created on Jan 17, 2011, 8:54:27 PM
 */

package gui;

/**
 *This class is used for log panel.
 *
 *
 * @author Shobhit
 */
public class LogPanel extends javax.swing.JFrame {

    private static LogPanel ref;

    /** Creates new form LogPanel */
    public LogPanel() {
        initComponents();
    }

    public static synchronized LogPanel getLogPanelInstance()
    {
      if (ref == null)

          ref = new LogPanel();
        return ref;
    }

    public synchronized void logMessage(String message)
    {
        textAreaTransferLogs.append(message);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaTransferLogs = new javax.swing.JTextArea();
        buttonClearLogs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textAreaTransferLogs.setColumns(20);
        textAreaTransferLogs.setRows(5);
        jScrollPane1.setViewportView(textAreaTransferLogs);

        buttonClearLogs.setText("Clear Logs");
        buttonClearLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearLogsActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                    .add(buttonClearLogs))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(buttonClearLogs))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClearLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearLogsActionPerformed
        // TODO add your handling code here:
        textAreaTransferLogs.setText("");
    }//GEN-LAST:event_buttonClearLogsActionPerformed

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogPanel().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClearLogs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaTransferLogs;
    // End of variables declaration//GEN-END:variables

}
